name: Wangana
description:  Jekyll theme

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: kramdown

url: http://iterater.github.io
permalink: /:year/:month/:title/
owner:
    name: Sergey V. Kovalchuk
    twitter: iterater
    github: iterater
    disqus_shortname: #

ga_id: #
ga_username: #

timezone: Africa/Accra