theme: minima
title: Sergey V. Kovalchuk
description: Powered by GitHub Pages, Jekyll, Minima theme
twitter_username: iterater
github_username: iterater
author: Sergey V. Kovalchuk
google_analytics: UA-210876536-1
include: 
  - "education/rl_practice/_static"
  - "education/rl_practice/_images"
  - "education/rl_practice/_sources"
  - "education/rl_practice/_sphinx_design_static"
header_pages:
  - index.md
  - research.md
  - lab.md
  - publications.md
  - teaching.md
  - community.md
